services:
  mysql:
    container_name: dev-mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - "./docker_data/mysql:/var/lib/mysql"
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Root.123456

  redis:
    container_name: dev-redis
    image: redis:7.2.5
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]

  xxl_job:
    container_name: dev-xxl_job
    image: xuxueli/xxl-job-admin:2.4.1
    volumes:
      - "./docker_data/xxl_job:/data/applogs"
    ports:
     - 8991:8080
    environment:
      PARAMS: >-
        --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root
        --spring.datasource.password=Root.123456
        --xxl.job.accessToken=pkmer_token
    depends_on:
      - mysql