services:
  mysql:
    container_name: dev-mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - "./docker_data/mysql:/var/lib/mysql"
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Root.123456
      - MYSQL_DATABASE=taskdb

  redis:
    container_name: dev-redis
    image: redis:7.2.5
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]